### ISSUE TITLE
What is the purpose of the of the schemas and the jsonld.twig router?

### ISSUE THREAD

**Issue by iuscare** [miranj/craft-boilerplate#4]
Hi there, just a small question: it seems that you improved the template structure/functionality since your talk at Dot All 2018 and that you've added schemas and a jsonld router. Would you mind to explain the purpose of these new features, because your modular understanding often goes hand in hand with a deep understanding and sense how to structure the site in a modular way

**Comment by pl-mnm** [comment]
Hi @iuscare,

This addition to our modular templating system enables us to output JSON-LD structures for [schema.org schema types](https://schema.org/docs/schemas.html) on any page of the site. We use this along with the [SEOmate](http://github.com/vaersaagod/seomate) plugin.

The templates in `_schemas/details` are views, just like  `_views/details` or `_views/snippets` in [our modular architecture](https://miranj.in/blog/2019/modular-architecture-for-building-content-websites), and get routed in the same way. The role of the `details` templates is to assign values to an object with all the required schema properties (`schemaProps`) and call the right `_schemas/definition/` template.


    {# _schemas/details/blog #}
    {% extends '_schemas/details/default.twig' %}
    
    {% set schemaProps = {
      authors: entry.authors|all|map(a => { name: a.title, type: 'person' }),
    } %}
    
    {% block entry_schema %}
      {% from '_schemas/definitions/article' import article %}
      {% do graph.add(article(schemaProps)) %}
      
      {{ parent() }}
    {% endblock %}

Each `_schemas/definitions` template is a macro which can inherit values from other macros, in the same way schema types can inherit properties from other schema types. The macro assigns the right schema type and merges all properties into a single object before returning it to either another macro or back to `_schemas/detail/default`.

(We use the [Twig Perversion plugin](https://github.com/marionnewlevant/craft-twig_perversion) to return objects from macros).


    {% macro creativeWork(props, schema = null) %}
      {% from '_schemas/definitions/thing' import thing %}
      
      {% set schema = schema ?? craft.schema.CreativeWork %}
      {% set schema = thing(props, schema) %}
      {% set schema = schema
        .author(props.authors|default(null))
        .dateCreated(props.datePublished|default(null))
        .datePublished(props.datePublished|default(null))
        .dateModified(props.dateModified|default(null))
      %}
      
      {% return schema %}
    {% endmacro %}

The output of the last chained macro is then merged with default values in the extended `_schemas/details/default` before being output in the main view.


    {# _schemas/details/default #}
    {% set defaultSchemaProps = {
      title: entry.title,
      url: entry.url,
    } %}
    {% set schemaProps = schemaProps ?? {} %}
    {% set schemaProps = defaultSchemaProps|merge(schemaProps) %}
    
    {% block entry_schema %}
      {% from '_schemas/definitions/webpage' import webpage %}
      {% do graph.add(webpage(schemaProps)) %}
      
      {{ graph|raw }}
    {% endblock %}

I hope that helps clearing things up.
