### ISSUE TITLE
Add common fallback image for imager

### ISSUE THREAD

**Issue by anita-chouhan** [miranj/craft-boilerplate#92]
Reference: [https://miranj.slack.com/archives/C015CEJT1AS/p1716399907362749](https://miranj.slack.com/archives/C015CEJT1AS/p1716399907362749)

Usage reference: ADB ['fallbackImage' => 'https://placehold.co/1800x1200.png',]

We can set these config options in the dev env array on config/imager-x.php. https://imager-x.spacecat.ninja/configuration.html#fallbackimage-int-string-asset (edited) 

![image (24)](https://github.com/miranj/craft-boilerplate/assets/30666052/b48bec29-b95a-4cb2-8e2a-5be745487341)

**Comment by rungta** [comment]
Fixed in b38b5de980f423ae9abf6f485b6bce15d9e297d3

**Comment by rungta** [comment]
Fixed in b38b5de980f423ae9abf6f485b6bce15d9e297d3
