### ISSUE TITLE
Readme mentions "Ready made fields to import..." under "Features". Can't find file to import.

### ISSUE THREAD

**Issue by francismacomber** [miranj/craft-boilerplate#99]
First, thank you for an excellent boilerplate. It's awesome to see how other agencies structure their CraftCMS projects, especially with the new features in Craft5. 

It's possible I overlooked something. Your readme mentions ready to import fields which I was interested in taking a look at, but I wasn't able to find any db or json files to import in the repo. 

Is this something you still plan on adding for your v5 boilerplate? 

Thanks

**Comment by rungta** [comment]
Hi @francismacomber, glad to know you found our boilerplate useful. The ready-to-import fields are in the [`./field-library`](https://github.com/miranj/craft-boilerplate/tree/dev/field-library) folder (along with a [separate README](https://github.com/miranj/craft-boilerplate/tree/dev/field-library)) in the root of the repo. They may not all be up to date for Craft 5 though.

**Comment by francismacomber** [comment]
Thanks. I see it now. It's strange--for some reason when I created a new local project with the dev-dev composer package, it didn't get that folder.

**Comment by rungta** [comment]
@francismacomber That’s because earlier this year we decided to [remove the folder from new project repos](https://github.com/miranj/craft-boilerplate/commit/49257e0cac0d0866f563ae8b37962b08c479e1fc) and prefer accessing the field library via the boilerplate repo on GitHub.
